### PR TITLE
Fix compile error in visual studio 2017 update 5.

### LINKED ISSUE #37: Unable to compile with mysql connector/c 8.0
OS: windows
Arch: x64
Compiler: VS2017 Community Update 5
Connector: Mysql 8.0 Connector/C (installed with mysql server 8)
Standard: C++-17

In 8.0 they removed `my_bool` and replaced it with the normal `bool` type. This causes the library to fail comp.

https://dev.mysql.com/doc/refman/8.0/en/c-api-prepared-statement-data-structures.html

### PR DESCRIPTION
**Pull request by RavenX8**
OS: windows 
Arch: x64
Compiler: VS2017 Community Update 5
Connector: Mysql 5.7 Connector/C
Standard: C++-17
 
Fixes error: 
> sqlpp11-connector-mysql\include\sqlpp11/mysql/char_result.h(90): error C2146: syntax error: missing ')' before identifier 'or'
> sqlpp11-connector-mysql\include\sqlpp11/mysql/char_result.h(92): error C2146: syntax error: missing ')' before identifier 'or'
> sqlpp11-connector-mysql\include\sqlpp11/mysql/char_result.h(97): error C2146: syntax error: missing ')' before identifier 'or'
> sqlpp11-connector-mysql\include\sqlpp11/mysql/char_result.h(103): error C2146: syntax error: missing ')' before identifier 'or'
> sqlpp11-connector-mysql\include\sqlpp11/mysql/char_result.h(109): error C2146: syntax error: missing ')' before identifier 'or'
> sqlpp11-connector-mysql\include\sqlpp11/mysql/char_result.h(115): error C2146: syntax error: missing ')' before identifier 'or'
> sqlpp11-connector-mysql\include\sqlpp11/mysql/connection_config.h(53): error C2146: syntax error: missing ')' before identifier 'and'

This also fixes #37 on all platforms

### CODE REVIEW

File: src/detail/connection_handle.cpp [hunk 1]
```diff
@@ -35,6 +35,10 @@ namespace sqlpp
   {
     namespace detail
     {
+      #if LIBMYSQL_VERSION_ID > 80000
+        typedef bool my_bool;
```
Comment (rbock) [inline src/detail/connection_handle.cpp]: Please use `using my_bool = bool` instead to be in line with the rest of the code.

File: src/prepared_statement.cpp [hunk 2]
```diff
@@ -98,7 +98,7 @@ namespace sqlpp
       param.buffer = const_cast<uint64_t*>(value);
       param.buffer_length = sizeof(*value);
       param.length = &param.buffer_length;
-      param.is_null = &_handle->stmt_param_is_null[index];
+      param.is_null = (my_bool*)is_null;
```
Comment (rbock) [inline src/prepared_statement.cpp]: Why did you change this? c-style casting a bool to a pointer looks rather dangerous to me (even more so, considering that `is_null` is a temporary).

**Review by rbock — CHANGES_REQUESTED** [review]

File: src/prepared_statement.cpp (hunk 2 above)
Comment (RavenX8) [reply src/prepared_statement.cpp]: I had changed this because the compiler was erroring out on that line, saying that 
> &_handle->stmt_param_is_null[index]


was temporary. I don't agree with that statement but this was just a temp change while I tested the rest of the comp process.

Comment (RavenX8) [reply src/prepared_statement.cpp]: this is the error it throws:

>sqlpp11-connector-mysql/src/prepared_statement.cpp:69:57: error: cannot convert ‘std::vector<bool>::reference* {aka std::_Bit_reference*}’ to ‘bool*’ in assignment
sqlpp11-connector-mysql/src/prepared_statement.cpp: In member function ‘void sqlpp::mysql::prepared_statement_t::_bind_integral_parameter(size_t, const int64_t*, bool)’:
sqlpp11-connector-mysql/src/prepared_statement.cpp:85:57: error: taking address of temporary [-fpermissive]
       param.is_null = &_handle->stmt_param_is_null[index];

Comment (RavenX8) [reply src/prepared_statement.cpp]: Alright just found out that the reason why is because std::vector can not do what we are doing with booleans. that call instead of returning the address of the bool, it returns the address of a proxy object that IS temporary.

https://en.cppreference.com/w/cpp/container/vector_bool

File: src/detail/connection_handle.cpp (hunk 1 above)
Comment (RavenX8) [reply src/detail/connection_handle.cpp]: Fixed. Also maybe I should move this into it's own header as this block is in 2 files, src/detail/connection_handle.cpp and src/detail/prepared_statement_handle.h.

Let me know what you would prefer.

Comment (rbock) [reply src/detail/connection_handle.cpp]: Yes, I think it should be in a separate header, like `version_compatibility.h` maybe.

File: src/prepared_statement.cpp (hunk 2 above)
Comment (rbock) [reply src/prepared_statement.cpp]: Aaargh, yes, it worked before because of `my_bool != bool`.

I am confused by all the `reinterpret_cast`? I think we should just put something different into the vector, like a struct with just a my_bool/bool member.

**Comment by rbock** [comment]
I fixed the my_bool part in the meantime.

**Comment by RavenX8** [comment]
Oh so you made the change already? My only question on here was did you want me to move the my_bool def to it's own header file

**Comment by rbock** [comment]
Yes, I ran into the problem on travis-ci.

I did not fix the includes for MSVC, though.

**Comment by RavenX8** [comment]
I will be resubmitting this with only the fix for Windows.
